"""empty message

Revision ID: 1b136fa03e20
Revises: 4d325adb7717
Create Date: 2015-04-15 17:45:00.738972

"""

# revision identifiers, used by Alembic.
revision = '1b136fa03e20'
down_revision = '4d325adb7717'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_decks')
    op.drop_table('decks')
    op.drop_table('users')
    op.drop_table('flashcard_responses')
    op.drop_table('flashcards')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcards',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_text', sa.VARCHAR(length=256), nullable=True),
    sa.Column('question_answer', sa.VARCHAR(length=127), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcard_responses',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('response', sa.VARCHAR(length=127), nullable=True),
    sa.Column('flashcard_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['flashcard_id'], [u'flashcards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decks',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=127), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_decks',
    sa.Column('flashcard_id', sa.INTEGER(), nullable=True),
    sa.Column('deck_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], [u'decks.id'], ),
    sa.ForeignKeyConstraint(['flashcard_id'], [u'flashcards.id'], )
    )
    ### end Alembic commands ###
